# Generated by Django 6.1.1 on 2026-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('report_type', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Accessories', 'Accessories'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Returned', 'Returned')], default='Open', max_length=10)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
